"""fix column name

Revision ID: b1506921d9ab
Revises: d8e7ba485a24
Create Date: 2025-11-16 20:31:29.516719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1506921d9ab'
down_revision = 'd8e7ba485a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calorie_goal', sa.Float(), nullable=True))
        batch_op.drop_column('caloire_goal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caloire_goal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('calorie_goal')

    # ### end Alembic commands ###
