"""Add columns to user table

Revision ID: d8e7ba485a24
Revises: a8ca2eb68d6d
Create Date: 2025-11-16 20:29:47.527985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e7ba485a24'
down_revision = 'a8ca2eb68d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caloire_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fiber_goal', sa.Float(), nullable=True))
        batch_op.drop_column('daily_goal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_goal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('fiber_goal')
        batch_op.drop_column('protein_goal')
        batch_op.drop_column('caloire_goal')

    # ### end Alembic commands ###
